#!/usr/bin/env bash
# Setup minimalKioskOS
# Install Chromium and disable SSH
# Written by Sylvia van Os
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

set +x

apt-get update
# Install graphic libraries
apt-get install -y libgl1-mesa-dri mesa-utils

# Install Chromium
apt-get install -y rpi-chromium-mods

# Install Python dep
apt-get install -y python3-pip
pip3 install pychrome

# Disable SSH
rm /boot/ssh

# Auto-hide mouse support
apt-get install -y unclutter

set -x

# Unpack root at the end, so files are modified before
unpack /filesystem/root /
